services:
  api-gateway:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BENCHMARK_SERVICE_URL=benchmark-service:9093
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - ENV=development
    networks:
      - thesis-net

networks:
  thesis-net:
    external: false
    name: thesis-net